version: '3.8'

services:
  lazyautomation:
    build: .
    ports:
      - "${PORT:-3002}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REACT_APP_HASS_HOST=${REACT_APP_HASS_HOST}
      - REACT_APP_HASS_TOKEN=${REACT_APP_HASS_TOKEN}
      - REACT_APP_OLLAMA_HOST=${REACT_APP_OLLAMA_HOST}
      - REACT_APP_APP_URL=${REACT_APP_APP_URL}
    stdin_open: true
    tty: true
